### PR TITLE
Fix incorrect string formatting of float values in Verilator

### LINKED ISSUE #99: Shared float handling
Hello! I'm seeing some weird behavior on shared variables which are arrays of floats- it seems like they don't get written. See below for a minimal reproduction example. Is there a property my code is missing that's required to enable shared mutable state? The issue is also present for arrays of floats. I am on commit `32bdfac`.

```
import debug.print
import test.unit as unit
import test.runner
class count_if_testbench
            {
            private:
              float32[1]  _floatarr;
              int32[1]  _intarr;
              void Test()
              {
                _floatarr[0] = 1.0;
                _intarr[0] = 1;
                println("updated float arr within func is {_floatarr[0]}");
                println("updated int arr within func is {_intarr[0]}");
              }
            public:
              [[max_threads(1)]]
              void run(unit::tag_t tag)
              {
                Test();
                println("updated float arr within func is {_floatarr[0]}");
                println("updated int arr within func is {_intarr[0]}");

              }
}

  inline void test_main()
  {
    unit::test<1>(unit::fixture<count_if_testbench>());
  }

```
This prints
```
1: updated float arr within func is 0.000000
1: updated int arr within func is 1
1: updated float arr within func is 0.000000
1: updated int arr within func is 1
```

### PR DESCRIPTION
**Pull request by matthew-humphrey**
To fix this bug, the following changes were made:
- Added a new file, functions.sv, containing a package KanagawaFunctions, containing a SystemVerilog function, shortreal_bits_to_string to convert float values to strings. On Verilator, this function uses a workaround that leverages the real data type instead of shortreal (shortreal is not supported in Verilator).
- Replaced compiler generation of string formatting for float values to use the custom conversion function in KanagawaFunctions instead of directly using $bitstoshortreal.
- Updated hal_dsp.sv in the mock HAL to use functions in the new KanagawaFunctions package. These were moved there in order to leverage them in shortreal_bits_to_string.
- Adjusted test helper CMake file to ensure HAL files are included after the main RTL because now the HAL has a dependency on functions.sv.
- Removed conditional compilation in logic test Interpolation (25). This code was previously disabled for Verilator due to issues with $bitstoshortreal, but with the new conversion function, this is no longer necessary.
- Some dead code in Verilog.sv print handling was removed. The compiler only needs to emit code to handle string types, because string interpolation is used in a library function before the code makes it to the compiler's `print` implementation.

Closes #99

### CODE REVIEW

File: compiler/cpp/verilog.cpp [hunk 1]
```diff
@@ -9803,11 +9803,6 @@ class VerilogCompiler
             {
                 switch (printEntry._type)
                 {
-                case PrintType::Uint:
-                case PrintType::Int:
```
Comment (blakepelton) [inline compiler/cpp/verilog.cpp]: Are these cases not possible anymore?

File: runtime/rtl/functions.sv [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+            if (mant23 == 23'b0) begin
+                // Zero
+                exp11 = 11'h000;
+                mant52 = 52'b0;
+            end
+            else begin
+                // Denormalized - need to normalize for double precision
+                // This is a simplified handling - full denorm support would be more complex
+                exp11 = 11'h380; // Minimum exponent offset
+                mant52 = {mant23, 29'b0};
```
Comment (blakepelton) [inline runtime/rtl/functions.sv]: I guess this is to handle the case where the value is denorm in float32 but normalized in float64?  The denorm float32 mantissa does not have an implicit 1, whereas I think the float64 mantissa would have an implicit 1, is that a problem?

File: compiler/cpp/verilog.cpp (hunk 1 above)
Comment (blakepelton) [reply compiler/cpp/verilog.cpp]: Oh awesome.  I see there are `assert(false)` just in case, seems good.

File: runtime/rtl/functions.sv (hunk 2 above)
Comment (matthew-humphrey) [reply runtime/rtl/functions.sv]: I tested these functions with some code written in C/C++ that generated test cases, but that code didn't make it into the OSS repo. Let me look into this.

Comment (matthew-humphrey) [reply runtime/rtl/functions.sv]: Yes, you are right. Update with test cases coming soon.
